[DATABASE]
filename = dispatch.db

[DISCORD]
bot_token = 
first_aid_channel = 1510743272291696721
# NOTE: The bot is READ-ONLY and strictly routes to First Aid.
# It will ONLY post to Discord if the code is: Blue or Yellow.

[APPLICATION]
auto_refresh_seconds = 10
auto_scroll_to_latest = True

[BACKUP]
max_backups = 10

[USERS]
kx = admin
ap = admin
ec = admin
iy = admin
dispatcher1 = user

[SOURCES]
# Removed Code Adam from this list!
Radio = General, Safety, First Aid
Social Media = Discord, Phone Call, SMS

[CODES]
General Situations = No_Code | General situations and non-specific reports.
Supervisor Request = Green | Requesting supervisor backup.
Spill = Brown | Chemical or liquid spills.
Technical Failure = Orange | Equipment or technical failure.
Fire = Red | Smoke, flames, or fire report.
First Aid Request = Yellow | Minor medical issue or first aid request.
Medical Emergency = Blue | Critical medical emergency.
Harassment = Purple | Harassment reports.
Lost Child = Adam | Missing or lost child report.
Active Threat / Violence = White / Mayday | Active threat or violence.
Active Killer = Silver | Active killer on scene.
Bomb / Suspicious Package = Black | Bomb threats or suspicious items discovered.